### PR TITLE
Timeline to admin resources

### LINKED ISSUE #495: Timeline to admin resources

### PR DESCRIPTION
**Pull request by FelixLoether**
Closes #495.

### CODE REVIEW

**Comment by lraivio** [comment]
- [ ] You could also remove the old ResourceTable related translations.

**Comment by lraivio** [comment]
- [ ] It would be nice to use the selected date when going to a resource page from my resources page. This can be done in a separate issue however.

**Comment by FelixLoether** [comment]
Fixed.

**Comment by lraivio** [comment]
- [ ] Very nice! You could still squash the two linting error fixes together. Then ready for merge.

**Comment by FelixLoether** [comment]
Squashed.

**Pull request merged**
