### PR TITLE
Feature/561 reservation time edit

### LINKED ISSUE #561: Date and time editing to reservation info modal

### PR DESCRIPTION
**Pull request by lraivio**
This PR adds reservation time editing to reservation edit form in info modals.
Validation and error handling is kept very light on purpose and relies heavily on the status notifications.

Closes #561.

### CODE REVIEW

**Comment by YoYuUm** [comment]
There are couple of small things I don't know if they are intended.

- [ ] The time FormControl step works when updating minutes, but if you click 2 times I would spect a change of hour eg. pressing up arrow button (12:00 -> 12:30 -> 13:00) But what currently happens is (12:00 -> 12:30 -> 12:00)

- [ ] If you cancel the edit, the state of the edited fields persist. So if you click again on edit the previous changes are still there.

**Comment by lraivio** [comment]
The issues you mentioned @YoYuUm have now been fixed.

**Comment by YoYuUm** [comment]
- [ ] It's possible to change edit the reservation to be outside opening hours. Backend also allows it. I've tried to edit a reservation so it overlaps with another reservation but the backend doesn't allow this, and an error pops up. Perhaps it would be better if the backend would take care of the reservations outside opened hours as well if the changes for showing only opened hours are too complicated.

**Comment by YoYuUm** [comment]
Very nice improvement on time selector ;)

**Comment by lraivio** [comment]
Good catch! I didn't realize the API allows making reservations outside of opening hours. Preventing this in the frontend is probably not top priority at the moment but I created a separate issue (#580) for it so we don't forget.

**Pull request merged**
