### PR TITLE
[Fix/Upgrade] Upgrade date pickers

### PR DESCRIPTION
**Pull request by Nizar-Rahme**

### CODE REVIEW

**Comment by Nizar-Rahme** [comment]
[Replace react-date-picker package](https://trello.com/c/As9eGRJA/23-replace-react-date-picker-package)

**Comment by Nizar-Rahme** [comment]
@rBoost Yes, I have.
Though, I changed deliberately the styling of the date picker on `/admin-resources` page since it was using the default styles of the library and it didn't match other calendars. See the following screenshots: 

Old implementation:
screenshot 2019-03-06 at 9 42 12

Current one:
screenshot 2019-03-06 at 9 42 20

**Comment by rBoost** [comment]
@Nizar-Rahme Ok, what about the resource page "Reserve" date picker styles? I'm just making sure everything is working :)
screenshot 2019-03-06 at 9 58 39

**Comment by Nizar-Rahme** [comment]
Yep, it's identical to what was before. 
screenshot 2019-03-06 at 10 03 23

**Pull request merged**
